// KRA e-TIMS (electronic Tax Invoice Management System) — fiscal receipt
// issuance for B2B invoices, so a corporate buyer gets a KRA-compliant tax
// invoice number alongside TrioCraft's own invoice.
//
// IMPORTANT — read before wiring this to production: e-TIMS is not a single
// public REST API you can just call with an API key the way Daraja or Meta's
// Graph API work. KRA's OSCU/VSCU specification is typically integrated
// through a KRA-approved invoicing/ERP system or a certified middleware
// provider (your own VSCU device software, or a vendor like a licensed ETR
// supplier), and the exact request/response contract depends on which route
// you take. I do not have access to that specification or sandbox, so this
// module is a clearly-documented INTEGRATION POINT, not a tested client:
//
//   - Without ETIMS_API_URL / ETIMS_API_KEY set, issueFiscalInvoice() logs a
//     simulated fiscal invoice number to the console and returns a
//     success-shaped response, so the rest of the invoicing flow (PDF
//     generation, order record-keeping) is fully testable today.
//   - With those env vars set, it POSTs the invoice payload to whatever
//     ETIMS_API_URL you configure (your VSCU middleware's endpoint) and
//     expects back a JSON object containing an invoice/control-unit number.
//     Adjust the request/response shape in the try block below to match
//     your actual VSCU provider's contract before relying on it — treat this
//     as a starting point, not a certified integration.

const QRCode = require('qrcode');

const isConfigured = !!(process.env.ETIMS_API_URL && process.env.ETIMS_API_KEY);

// Renders a QR PNG (as a data: URL) from whatever payload string we have.
// In simulated mode the payload is deliberately unmissable as fake — it does
// NOT encode a KRA verification URL or anything a scanner could mistake for
// a real fiscal signature. In real mode we encode whatever verification
// string/URL the middleware provider returned.
async function renderQr(payload) {
  try {
    return await QRCode.toDataURL(payload, { margin: 1, width: 240, color: { dark: '#000000', light: '#FFFFFF' } });
  } catch (err) {
    console.error('[etims] QR render failed:', err.message);
    return null;
  }
}

/**
 * @param {{ orderId:number, buyerName:string, buyerPin:string, amount:number, items:Array<{description:string, quantity:number, unitPrice:number}> }} params
 * @returns {Promise<{ success:boolean, simulated?:boolean, invoiceNumber:string, controlNumber?:string, qrDataUrl?:string, reason?:string }>}
 */
async function issueFiscalInvoice({ orderId, buyerName, buyerPin, amount, items }) {
  if (!isConfigured) {
    const simNumber = `SIM-ETIMS-${orderId}-${Date.now()}`;
    const controlNumber = `CU-SIM-${String(orderId).padStart(4, '0')}-${Date.now().toString().slice(-6)}`;
    console.log('\n[etims] KRA e-TIMS not configured — simulating fiscal invoice:');
    console.log(`  Order:      #${orderId}`);
    console.log(`  Buyer:      ${buyerName}${buyerPin ? ' (PIN: ' + buyerPin + ')' : ' (no KRA PIN on file)'}`);
    console.log(`  Amount:     KES ${Math.round(amount).toLocaleString()}`);
    console.log(`  Sim. No.:   ${simNumber}`);
    console.log(`  Sim. CU No: ${controlNumber}`);
    console.log('[etims] Set ETIMS_API_URL / ETIMS_API_KEY in .env to issue real fiscal invoices via your VSCU/middleware provider.\n');
    const qrDataUrl = await renderQr(
      `SIMULATED — NOT A REAL KRA FISCAL RECEIPT\nOrder: TC-ORD-${orderId}\nSim. Invoice: ${simNumber}\nSim. Control No: ${controlNumber}\nAmount: KES ${Math.round(amount)}\nGenerated by TrioCraft's dev/staging invoicing flow — connect ETIMS_API_URL/ETIMS_API_KEY to issue a real one.`
    );
    return { success: true, simulated: true, invoiceNumber: simNumber, controlNumber, qrDataUrl };
  }

  try {
    const res = await fetch(process.env.ETIMS_API_URL, {
      method: 'POST',
      headers: { Authorization: `Bearer ${process.env.ETIMS_API_KEY}`, 'Content-Type': 'application/json' },
      body: JSON.stringify({ orderId, buyerName, buyerPin, amount: Math.round(amount), items }),
    });
    const data = await res.json().catch(() => ({}));
    if (!res.ok) return { success: false, reason: data?.message || `e-TIMS request rejected (${res.status})` };
    const invoiceNumber = data.invoiceNumber || data.cuInvoiceNumber;
    const controlNumber = data.controlNumber || data.cuNumber || null;
    // If the provider already returns a rendered QR image, use it as-is;
    // otherwise render one from whatever verification string it gave us.
    const qrDataUrl = data.qrImageUrl || (data.qrData ? await renderQr(data.qrData) : null);
    return { success: true, simulated: false, invoiceNumber, controlNumber, qrDataUrl };
  } catch (err) {
    console.error('[etims] Fiscal invoice issuance failed:', err.message);
    return { success: false, reason: err.message };
  }
}

module.exports = { issueFiscalInvoice, isConfigured };
